### ISSUE TITLE
Error when disconnecting vApp from networks pre-defined in the template

### ISSUE THREAD

**Issue by hardevsanghera** [vmware/vca-cli#14]
disconnecting vApp from networks pre-defined in the template
progress : [*************************                                                                           ]<Error message="[ b6276c54-b557-48f5-bc15-92dbfa04aeb1 ] Unable to perform this action. Contact your cloud administrator." minorErrorCode="INTERNAL_SERVER_ERROR" majorErrorCode="500"/>

vca --version
vca-cli version 12rc3 (pyvcloud: 13rc3)

**Comment by pacogomez** [comment]
This should be solved with the latest update (12rc9). Let me know otherwise.
