### ISSUE TITLE
Error when connecting VMs to network 

### ISSUE THREAD

**Issue by hardevsanghera** [vmware/vca-cli#15]
connecting VMs to network 'M86.....-4840-default-routed' with mode 'DHCP'
progress : [*************************                                                                           ]<Error message="[ c62f905c-bfd4-49f0-aeaa-4721c8250ada ] Unable to perform this action. Contact your cloud administrator." minorErrorCode="INTERNAL_SERVER_ERROR" majorErrorCode="500"/>

vca --version
vca-cli version 12rc3 (pyvcloud: 13rc3)

**Comment by pacogomez** [comment]
This should be solved with the latest update (12rc9). Let me know otherwise.
