### ISSUE TITLE
Document installation instructions do not always work

### ISSUE THREAD

**Issue by zjs** [vmware/vca-cli#4]
I've tried running the documented installation instructions:

```$ pip install vca-cli```

I've also tried running the command as `root` with `sudo`:

```$ sudo pip install vca-cli```

I received an error in both cases.

Log files can be found in this gist: https://gist.github.com/zjs/de5568ed08aa3240eef2

**Comment by pacogomez** [comment]
added documentation on the required packages, see:

https://github.com/vmware/vca-cli#installation

**Comment by pacogomez** [comment]
closing the issue, let me know if the new instructions work.
