### ISSUE TITLE
At least one example of vca login should demonstrate that passwords do not need to be supplied on the command line

### ISSUE THREAD

**Issue by zjs** [vmware/vca-cli#5]
If no password is provided on the command line, [the user will be prompted for one](https://github.com/vmware/vca-cli/blob/master/vca_cli/vca_cli.py#L128).

However, none of the [examples](https://github.com/vmware/vca-cli/blob/master/vca_cli/vca_cli.py#L751-L760) demonstrate this functionality, which may lead a user to believe it is necessary to supply their password on the command line (where it will likely be visible and logged).

**Comment by pacogomez** [comment]
Added example id6 to address this issue, and documented in the README https://github.com/vmware/vca-cli#usage

  6 | prompt user for password            | vca login email@company.com
