### ISSUE TITLE
Error messages should include relevant request ID

### ISSUE THREAD

**Issue by zjs** [vmware/vca-cli#6]
When an error occurs and is reported to the user, `vca-cli` should include the value of the `X-VMWARE-VCLOUD-REQUEST-ID` header from the relevant API response. If the user contacts support about the error, they can provide this value to allow support to quickly identify the relevant logs.

**Comment by pacogomez** [comment]
planning to add the request-id and the error message returned by vCD. in the meantime commands can be called with the -d or --debug flag to get that information

**Comment by pacogomez** [comment]
fixed in the new version 9
