### ISSUE TITLE
Error displaying status after login

### ISSUE THREAD

**Issue by jicowan** [vmware/vca-cli#8]
I'm getting errors when trying to display "vca status" (subscription).  The first response is for the login request using the command vca login <username@domain.com> --password <password> --host https://vchs.vmware.com --version 5.6 --type subscription. The second response is the output from "vca status" after I've been authenticated.  Interestingly, I have no trouble displaying the list of orgs using vca org list command, however, when I try setting the org to the name of my org it says "unable to select organization <organizationname> in profile. 

vca : INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): vchs.vmware.com
At line:1 char:1
+ vca -d login jcowan@vmware.com --password <mypassword> --type subscription --host ht ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (INFO:requests.p...vchs.vmware.com:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
DEBUG:requests.packages.urllib3.connectionpool:"POST /api/vchs/sessions HTTP/1.1" 201 204

send: 'POST /api/vchs/sessions HTTP/1.1\r\nHost: vchs.vmware.com\r\nContent-Length: 0\r\nAccept-Encoding: gzip, deflate\r\nAccept: application/xml;version=5.6\r\nUser-Agent: python-requests/2.4.3 CPython/2.7.8 Windows/8\r\nConnection: keep-alive\r\nAuthorization: Basic amNvd2FuQHZtd2FyZS5jb206ejBtQiEzeio=\r\n\r\n'
reply: 'HTTP/1.1 201 Created\r\n'
header: Date: Fri, 13 Feb 2015 15:41:48 GMT

header: Server: Apache-Coyote/1.1

header: x-vchs-authorization: 59266ce87ca751f84bb7be96666f1ef81e21aea9,c2b79fe0-c0a7-4da6-8658-b6f00d2d910b%3BVMware+Sales+Demo%3Ba36ecbfe-3000-4c95-a0d0-094d838fdcc8%3Bjcowan%40vmware.com%3B17501914-a57f-4db2-8f92-33e7478ce54b%3B1%3B1423842108937%3Btrue%3Bfalse

header: Content-Type: application/xml; class=vnd.vmware.vchs.session; version=5.6;charset=UTF-8

header: Vary: Accept-Encoding,User-Agent

header: Content-Encoding: gzip

header: X-Frame-Options: SAMEORIGIN

header: Content-Length: 204

header: Set-Cookie: ROUTEID=.132; path=/;Secure;HTTPOnly

header: Cache-Control: no-store,no-cache,must-revalidate

header: Pragma: no-cache

header: Keep-Alive: timeout=15, max=100

header: Connection: Keep-Alive

Login successful for profile 'default'
******************************************************************************************
vca : INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): vchs.vmware.com
At line:1 char:1
+ vca -d status 2>&1 > status.log
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (INFO:requests.p...vchs.vmware.com:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
DEBUG:requests.packages.urllib3.connectionpool:"GET /api/vchs/services HTTP/1.1" 200 489

send: 'GET /api/vchs/services HTTP/1.1\r\nHost: vchs.vmware.com\r\nConnection: keep-alive\r\nx-vchs-authorization: 59266ce87ca751f84bb7be96666f1ef81e21aea9,c2b79fe0-c0a7-4da6-8658-b6f00d2d910b%3BVMware+Sales+Demo%3Ba36ecbfe-3000-4c95-a0d0-094d838fdcc8%3Bjcowan%40vmware.com%3B17501914-a57f-4db2-8f92-33e7478ce54b%3B1%3B1423842108937%3Btrue%3Bfalse\r\nAccept-Encoding: gzip, deflate\r\nAccept: application/xml;version=5.6\r\nUser-Agent: python-requests/2.4.3 CPython/2.7.8 Windows/8\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Date: Fri, 13 Feb 2015 15:42:08 GMT

header: Server: Apache-Coyote/1.1

header: x-vchs-authorization: 07d5e905d52ad7b6d7938fc256097d99b55c1405,c2b79fe0-c0a7-4da6-8658-b6f00d2d910b%3BVMware+Sales+Demo%3Ba36ecbfe-3000-4c95-a0d0-094d838fdcc8%3Bjcowan%40vmware.com%3B17501914-a57f-4db2-8f92-33e7478ce54b%3B1%3B1423842128378%3Btrue%3Bfalse

header: Content-Type: application/xml; class=vnd.vmware.vchs.servicelist; version=5.6;charset=UTF-8

header: Vary: Accept-Encoding,User-Agent

header: Content-Encoding: gzip

header: X-Frame-Options: SAMEORIGIN

header: Content-Length: 489

header: Set-Cookie: ROUTEID=.132; path=/;Secure;HTTPOnly

header: Cache-Control: no-store,no-cache,must-revalidate

header: Pragma: no-cache

header: Keep-Alive: timeout=15, max=100

header: Connection: Keep-Alive

Traceback (most recent call last):
  File "C:\Python27\Scripts\vca-script.py", line 9, in <module>
    load_entry_point('vca-cli==6', 'console_scripts', 'vca')()
  File "C:\Python27\lib\site-packages\click\core.py", line 610, in __call__
    return self.main(*args, **kwargs)
  File "C:\Python27\lib\site-packages\click\core.py", line 590, in main
    rv = self.invoke(ctx)
  File "C:\Python27\lib\site-packages\click\core.py", line 936, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Python27\lib\site-packages\click\core.py", line 782, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Python27\lib\site-packages\click\core.py", line 416, in invoke
    return callback(*args, **kwargs)
  File "C:\Python27\lib\site-packages\vca_cli\vca_cli.py", line 247, in status
    if property == 'password' and len(ctx.obj[property])>0:
TypeError: object of type 'NoneType' has no len()

**Comment by pacogomez** [comment]
will fix it in the next update. in the meantime please use the --save-password flag in the login command
